spring:
  rsocket:
    server:
      port: 3000
      ssl:
        enabled: true
        client-auth: NEED
        key-store: "classpath:server-keystore.p12"
        key-store-type: "PKCS12"
        key-store-password: "changeit"
        trust-store: "classpath:truststore.p12"
        trust-store-password: "changeit"
  main:
    lazy-initialization: true
logging:
  reactor:
    netty:
      tcp:
        SslProvider: debug
        ssl: debug


