logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: client1
server:
  port: 7001
rsocket:
  remote:
    port: 3000
    host: localhost
  jwt:
    audience: client2
    subject: client1
  ssl:
    server:
      trustStoreName: truststore.p12
      trustStorePassword: changeit
    client:
      keyStoreName: client-keystore.p12
      keyStorePassword: changeit

---
spring:
  config:
    activate:
      on-profile: client2
server:
  port: 7002
rsocket:
  remote:
    port: 3000
    host: localhost
  jwt:
    audience: client1
    subject: client2
  ssl:
    server:
      trustStoreName: truststore.p12
      trustStorePassword: changeit
    client:
      keyStoreName: client2-keystore.p12
      keyStorePassword: changeit